# Site settings
title: Águas Futuras
email: renatocoutinho+cantareira@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Projeções para o reservatório da Cantareira
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cantareira.github.io" # the base hostname & protocol for your site
github_username: cantareira

# Build settings
markdown: kramdown
